spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/personality
    username: user
    password: postgres
    h2:
      console:
        enabled: true # jeśli używasz H2 do celów deweloperskich
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect