spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Coltrane1443
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
server:
  port: 8082